export const Users = [
    {
      id:1,
      profilePicture: "assets/persons/person1.jpg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "assets/persons/person2.jpg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "assets/persons/person3.jpg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "assets/persons/person4.jpg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "assets/persons/person5.jpg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "assets/persons/person6.jpg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "assets/persons/person7.jpg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "assets/persons/person1.jpg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "assets/persons/person3.jpg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "assets/persons/person5.jpg",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/posts/chicken1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/posts/chicken2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Love u all",
      photo: "assets/posts/chicken3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/posts/omlette.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/posts/pasta.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/posts/pizza(1).jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/posts/pizza(2).jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/posts/sandwich.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/posts/sandwich2.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/posts/chicken1.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];